### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by LazySlavik** [hogepiyosan/RTSS_Timer#1]
Hello, I modified your app a little to do what I need, so far it works fine. 
Now I would like to add a file i/o and when i'm using fopen and fclose i get a linker error:
error LNK2019: unresolved external symbol _fclose referenced in function "unsigned long __stdcall ThreadProc(void *)" (?ThreadProc@@YGKPAX@Z)
error LNK2019: unresolved external symbol _fopen referenced in function "unsigned long __stdcall ThreadProc(void *)" (?ThreadProc@@YGKPAX@Z)
Could you explain, what causing that and maybe how could I work around that?

**Comment by ShittyCodeMan** [comment]
RTSS_Timer uses NODEFAULTLIB linker option for smaller exe file.
So remove this:
https://github.com/ShittyCodeMan/RTSS_Timer/blob/097dcc9d71f07f21d5b365e880d5690fbe6c5d88/RTSS_Timer.cpp#L4-L5
And change this line to `void WinMain()`:
https://github.com/ShittyCodeMan/RTSS_Timer/blob/097dcc9d71f07f21d5b365e880d5690fbe6c5d88/RTSS_Timer.cpp#L24
